# https://github.com/behaviorbot/welcome
# https://github.com/behaviorbot/request-info

newIssueWelcomeComment: |
  Thanks for opening your first issue here! ðŸ’–
  Be sure to follow the issue template ðŸ‘Œ.

newPRWelcomeComment: |
  Thanks for opening this pull request! ðŸ˜
  Please be patient and we will get back to you as soon as we can. ðŸ¤
  In the meantime, please check out our [Contributing Guidelines](./.github/CONTRIBUTING.md).

firstPRMergeComment: |
  Congrats on merging your first pull request! ðŸŽ‰
  We are proud of you! ðŸ«¶

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!

requestInfoDefaultTitles:
  - update
  - updates

requestInfoLabelToAdd: needs-more-info

checkIssueTemplate: true

checkPullRequestTemplate: true

requestInfoOn:
  issue: true
  pullRequest: true

requestInfoUserstoExclude:
  - astrochemx
