blank_issues_enabled: false

contact_links:
  - name: ğŸ—£ï¸ Discussion
    url: https://github.com/astrochemx/astrorepo/discussions
    about: Discuss with other community members
  - name: ğŸ™‹ Question
    url: https://github.com/astrochemx/astrorepo/discussions/new?category=q-a
    about: Ask questions other community members
  - name: ğŸ’¡ Feature or documentation request
    url: https://github.com/astrochemx/astrorepo/discussions/new?category=ideas
    about: Open a feature or documentation request, or propose an idea
